# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: akazarya <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/02/24 20:20:08 by akazarya          #+#    #+#              #
#    Updated: 2022/03/14 22:53:10 by akazarya         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =			libft.a
CC =			cc
CFLAGS =		-Wall -Wextra -Werror
RM =			/bin/rm -f
OPTION =		-c -I libft.h
SRCS =			ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c \
	ft_isascii.c ft_isdigit.c ft_isprint.c ft_itoa.c ft_memccpy.c ft_memchr.c \
	ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c ft_putchar_fd.c \
	ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_split.c ft_strcat.c ft_strchr.c \
	ft_strdup.c ft_striteri.c ft_strjoin.c ft_strlcat.c ft_strlcpy.c ft_strlen.c \
	ft_strmapi.c ft_strncmp.c ft_strnstr.c ft_strrchr.c ft_strtrim.c \
	ft_substr.c ft_tolower.c ft_toupper.c ft_strcmp.c ft_strcpy.c \
	get_next_line.c ft_sqrt.c ft_strstr.c
OBJS =			${SRCS:.c=.o}
BONUS =			ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c \
	ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c
BONUS_OBJS =	${BONUS:.c=.o}

%.o: %.c 
	@$(CC) $(CFLAGS) -c $< -o $(<:.c=.o)
	
all: 		${NAME}

$(NAME):	${OBJS}

			@ar rc ${NAME} ${OBJS}
clean:
			@${RM} ${OBJS} $(BONUS_OBJS)

fclean: clean
			@${RM} ${NAME}

re: fclean all

bonus:		${OBJS} ${BONUS_OBJS}
			@ar rc ${NAME} ${OBJS} ${BONUS_OBJS}

.PHONY:		all clean fclean re